version: '3'

services:
  postgres:
    image: 'postgres:15.3'
    container_name: 'java_postgres'
    environment:
      - 'POSTGRES_USER=***'
      - 'POSTGRES_PASSWORD=***'
      - 'POSTGRES_DB=data_base_telegram'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
